# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QHBoxLayout,
    QLabel, QLineEdit, QListView, QListWidget,
    QListWidgetItem, QMainWindow, QPushButton, QSizePolicy,
    QStackedWidget, QStatusBar, QTextBrowser, QTextEdit,
    QVBoxLayout, QWidget)
import Resources_rc

class Ui_AppUI(object):
    def setupUi(self, AppUI):
        if not AppUI.objectName():
            AppUI.setObjectName(u"AppUI")
        AppUI.resize(900, 640)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AppUI.sizePolicy().hasHeightForWidth())
        AppUI.setSizePolicy(sizePolicy)
        AppUI.setMinimumSize(QSize(900, 640))
        AppUI.setMaximumSize(QSize(900, 640))
        font = QFont()
        font.setFamilies([u"Barlow"])
        font.setPointSize(10)
        AppUI.setFont(font)
        self.Main = QWidget(AppUI)
        self.Main.setObjectName(u"Main")
        self.MainStack = QStackedWidget(self.Main)
        self.MainStack.setObjectName(u"MainStack")
        self.MainStack.setGeometry(QRect(0, 0, 901, 641))
        self.MainStack.setStyleSheet(u"")
        self.DashboardPage = QWidget()
        self.DashboardPage.setObjectName(u"DashboardPage")
        self.DashboardPage.setStyleSheet(u"QWidget#DashboardPage{\n"
"	background-color: rgb(74, 88, 89);\n"
"}")
        self.label = QLabel(self.DashboardPage)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(100, 10, 611, 71))
        font1 = QFont()
        font1.setFamilies([u"Barlow"])
        font1.setPointSize(30)
        font1.setBold(True)
        self.label.setFont(font1)
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Db_monitor_btn = QPushButton(self.DashboardPage)
        self.Db_monitor_btn.setObjectName(u"Db_monitor_btn")
        self.Db_monitor_btn.setGeometry(QRect(40, 180, 211, 61))
        font2 = QFont()
        font2.setFamilies([u"Barlow"])
        font2.setPointSize(15)
        font2.setBold(True)
        self.Db_monitor_btn.setFont(font2)
        self.Db_monitor_btn.setStyleSheet(u"background-color: rgb(200, 62, 77);")
        self.profile_label = QLabel(self.DashboardPage)
        self.profile_label.setObjectName(u"profile_label")
        self.profile_label.setGeometry(QRect(800, 20, 51, 51))
        self.profile_label.setStyleSheet(u"border-image: url(:/AppResources/scientist.png);")
        self.username_label = QLabel(self.DashboardPage)
        self.username_label.setObjectName(u"username_label")
        self.username_label.setGeometry(QRect(770, 70, 121, 21))
        self.username_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.username_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Db_Logout_btn = QPushButton(self.DashboardPage)
        self.Db_Logout_btn.setObjectName(u"Db_Logout_btn")
        self.Db_Logout_btn.setGeometry(QRect(790, 100, 71, 24))
        font3 = QFont()
        font3.setFamilies([u"Segoe UI"])
        font3.setPointSize(9)
        font3.setBold(True)
        self.Db_Logout_btn.setFont(font3)
        self.Db_Logout_btn.setStyleSheet(u"background-color: rgb(156, 196, 178);")
        self.Db_inference_btn = QPushButton(self.DashboardPage)
        self.Db_inference_btn.setObjectName(u"Db_inference_btn")
        self.Db_inference_btn.setGeometry(QRect(40, 270, 211, 61))
        self.Db_inference_btn.setFont(font2)
        self.Db_inference_btn.setStyleSheet(u"background-color: rgb(200, 62, 77);")
        self.Db_analysis_btn = QPushButton(self.DashboardPage)
        self.Db_analysis_btn.setObjectName(u"Db_analysis_btn")
        self.Db_analysis_btn.setGeometry(QRect(670, 270, 211, 61))
        self.Db_analysis_btn.setFont(font2)
        self.Db_analysis_btn.setStyleSheet(u"background-color: rgb(200, 62, 77);")
        self.Db_help_btn = QPushButton(self.DashboardPage)
        self.Db_help_btn.setObjectName(u"Db_help_btn")
        self.Db_help_btn.setGeometry(QRect(670, 360, 211, 61))
        self.Db_help_btn.setFont(font2)
        self.Db_help_btn.setStyleSheet(u"background-color: rgb(200, 62, 77);")
        self.Db_aboutus_btn = QPushButton(self.DashboardPage)
        self.Db_aboutus_btn.setObjectName(u"Db_aboutus_btn")
        self.Db_aboutus_btn.setGeometry(QRect(670, 450, 211, 61))
        self.Db_aboutus_btn.setFont(font2)
        self.Db_aboutus_btn.setStyleSheet(u"background-color: rgb(200, 62, 77);")
        self.Db_settings_btn = QPushButton(self.DashboardPage)
        self.Db_settings_btn.setObjectName(u"Db_settings_btn")
        self.Db_settings_btn.setGeometry(QRect(670, 180, 211, 61))
        self.Db_settings_btn.setFont(font2)
        self.Db_settings_btn.setStyleSheet(u"background-color: rgb(200, 62, 77);")
        self.Db_Alert_btn = QPushButton(self.DashboardPage)
        self.Db_Alert_btn.setObjectName(u"Db_Alert_btn")
        self.Db_Alert_btn.setGeometry(QRect(40, 360, 211, 61))
        self.Db_Alert_btn.setFont(font2)
        self.Db_Alert_btn.setStyleSheet(u"background-color: rgb(200, 62, 77);")
        self.Db_models_btn = QPushButton(self.DashboardPage)
        self.Db_models_btn.setObjectName(u"Db_models_btn")
        self.Db_models_btn.setGeometry(QRect(40, 450, 211, 61))
        self.Db_models_btn.setFont(font2)
        self.Db_models_btn.setStyleSheet(u"background-color: rgb(200, 62, 77);")
        self.Db_management_btn = QPushButton(self.DashboardPage)
        self.Db_management_btn.setObjectName(u"Db_management_btn")
        self.Db_management_btn.setGeometry(QRect(40, 540, 211, 61))
        self.Db_management_btn.setFont(font2)
        self.Db_management_btn.setStyleSheet(u"background-color: rgb(200, 62, 77);")
        self.DB_error_label = QLabel(self.DashboardPage)
        self.DB_error_label.setObjectName(u"DB_error_label")
        self.DB_error_label.setGeometry(QRect(330, 570, 551, 21))
        font4 = QFont()
        font4.setFamilies([u"Segoe UI"])
        font4.setPointSize(15)
        self.DB_error_label.setFont(font4)
        self.DB_error_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.MainStack.addWidget(self.DashboardPage)
        self.AlertPage = QWidget()
        self.AlertPage.setObjectName(u"AlertPage")
        self.AlertPage.setStyleSheet(u"QWidget#AlertPage{\n"
"background-color: rgb(200, 62, 77)\n"
"}")
        self.label_11 = QLabel(self.AlertPage)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(280, 10, 321, 71))
        self.label_11.setFont(font1)
        self.label_11.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.alertpage_back_btn = QPushButton(self.AlertPage)
        self.alertpage_back_btn.setObjectName(u"alertpage_back_btn")
        self.alertpage_back_btn.setGeometry(QRect(820, 10, 75, 31))
        font5 = QFont()
        font5.setFamilies([u"Barlow"])
        font5.setPointSize(9)
        font5.setBold(True)
        self.alertpage_back_btn.setFont(font5)
        self.alertpage_back_btn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 55, 59);")
        self.alert_details_input = QTextEdit(self.AlertPage)
        self.alert_details_input.setObjectName(u"alert_details_input")
        self.alert_details_input.setGeometry(QRect(200, 250, 541, 181))
        self.label_12 = QLabel(self.AlertPage)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(90, 140, 111, 31))
        font6 = QFont()
        font6.setFamilies([u"Barlow"])
        font6.setPointSize(12)
        font6.setBold(False)
        self.label_12.setFont(font6)
        self.label_12.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.alert_team_input = QComboBox(self.AlertPage)
        self.alert_team_input.addItem("")
        self.alert_team_input.addItem("")
        self.alert_team_input.addItem("")
        self.alert_team_input.addItem("")
        self.alert_team_input.addItem("")
        self.alert_team_input.addItem("")
        self.alert_team_input.addItem("")
        self.alert_team_input.addItem("")
        self.alert_team_input.setObjectName(u"alert_team_input")
        self.alert_team_input.setGeometry(QRect(200, 140, 161, 31))
        self.label_13 = QLabel(self.AlertPage)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(150, 190, 41, 31))
        self.label_13.setFont(font6)
        self.label_13.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.alert_title_input = QLineEdit(self.AlertPage)
        self.alert_title_input.setObjectName(u"alert_title_input")
        self.alert_title_input.setGeometry(QRect(200, 190, 541, 31))
        self.label_16 = QLabel(self.AlertPage)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(140, 240, 61, 31))
        self.label_16.setFont(font6)
        self.label_16.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.alert_send_btn = QPushButton(self.AlertPage)
        self.alert_send_btn.setObjectName(u"alert_send_btn")
        self.alert_send_btn.setGeometry(QRect(200, 460, 75, 31))
        self.alert_send_btn.setFont(font5)
        self.alert_send_btn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 55, 59);")
        self.alert_error_label = QLabel(self.AlertPage)
        self.alert_error_label.setObjectName(u"alert_error_label")
        self.alert_error_label.setGeometry(QRect(300, 470, 431, 20))
        font7 = QFont()
        font7.setFamilies([u"Segoe UI"])
        font7.setPointSize(12)
        font7.setBold(True)
        self.alert_error_label.setFont(font7)
        self.alert_error_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.MainStack.addWidget(self.AlertPage)
        self.loginPage = QWidget()
        self.loginPage.setObjectName(u"loginPage")
        self.loginPage.setStyleSheet(u"QWidget#loginPage{\n"
"	\n"
"	background-color: rgb(50, 55, 59);\n"
"}")
        self.label_4 = QLabel(self.loginPage)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(140, 180, 311, 231))
        self.label_4.setStyleSheet(u"background-color: rgb(74, 88, 89);\n"
" border: 2px solid red;")
        self.label_5 = QLabel(self.loginPage)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(240, 180, 101, 41))
        font8 = QFont()
        font8.setFamilies([u"Barlow"])
        font8.setPointSize(20)
        font8.setBold(True)
        self.label_5.setFont(font8)
        self.label_5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(self.loginPage)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(160, 240, 61, 31))
        self.label_6.setFont(font7)
        self.label_6.setStyleSheet(u"color: rgb(244, 214, 204);")
        self.userid_input = QLineEdit(self.loginPage)
        self.userid_input.setObjectName(u"userid_input")
        self.userid_input.setGeometry(QRect(250, 240, 181, 31))
        font9 = QFont()
        font9.setFamilies([u"Barlow"])
        font9.setPointSize(10)
        font9.setBold(False)
        self.userid_input.setFont(font9)
        self.label_7 = QLabel(self.loginPage)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(160, 290, 81, 31))
        font10 = QFont()
        font10.setFamilies([u"Barlow"])
        font10.setPointSize(12)
        font10.setBold(True)
        self.label_7.setFont(font10)
        self.label_7.setStyleSheet(u"color: rgb(244, 214, 204);")
        self.userid_input_2 = QLineEdit(self.loginPage)
        self.userid_input_2.setObjectName(u"userid_input_2")
        self.userid_input_2.setGeometry(QRect(250, 290, 181, 31))
        self.userid_input_2.setFont(font9)
        self.userid_input_2.setEchoMode(QLineEdit.EchoMode.Password)
        self.loginbtn = QPushButton(self.loginPage)
        self.loginbtn.setObjectName(u"loginbtn")
        self.loginbtn.setGeometry(QRect(260, 360, 81, 31))
        self.loginbtn.setFont(font10)
        self.loginbtn.setStyleSheet(u"background-color: rgb(200, 62, 77);")
        self.login_error_label = QLabel(self.loginPage)
        self.login_error_label.setObjectName(u"login_error_label")
        self.login_error_label.setGeometry(QRect(200, 330, 221, 16))
        font11 = QFont()
        font11.setFamilies([u"Segoe UI"])
        font11.setPointSize(10)
        font11.setBold(True)
        self.login_error_label.setFont(font11)
        self.login_error_label.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.login_error_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.MainStack.addWidget(self.loginPage)
        self.AboutusPage = QWidget()
        self.AboutusPage.setObjectName(u"AboutusPage")
        self.AboutusPage.setStyleSheet(u"QWidget#AboutusPage{\n"
"	\n"
"	background-color: rgb(50, 55, 59);\n"
"}")
        self.aboutus_back_btn = QPushButton(self.AboutusPage)
        self.aboutus_back_btn.setObjectName(u"aboutus_back_btn")
        self.aboutus_back_btn.setGeometry(QRect(810, 20, 75, 31))
        self.aboutus_back_btn.setFont(font5)
        self.aboutus_back_btn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.label_17 = QLabel(self.AboutusPage)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(70, 50, 650, 500))
        self.label_17.setFont(font2)
        self.label_17.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_17.setTextFormat(Qt.TextFormat.MarkdownText)
        self.label_17.setScaledContents(False)
        self.label_17.setWordWrap(True)
        self.label_17.setIndent(5)
        self.MainStack.addWidget(self.AboutusPage)
        self.EnginePage = QWidget()
        self.EnginePage.setObjectName(u"EnginePage")
        self.EnginePage.setStyleSheet(u"QWidget#EnginePage{background-color: rgb(200, 62, 77);}")
        self.label_2 = QLabel(self.EnginePage)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(280, 0, 421, 71))
        self.label_2.setFont(font1)
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ForestMapView = QLabel(self.EnginePage)
        self.ForestMapView.setObjectName(u"ForestMapView")
        self.ForestMapView.setGeometry(QRect(80, 80, 741, 491))
        self.ForestMapView.setStyleSheet(u"border-image: url(:/AppResources/ForestMap.jpg);")
        self.CT1_btn = QPushButton(self.EnginePage)
        self.CT1_btn.setObjectName(u"CT1_btn")
        self.CT1_btn.setGeometry(QRect(520, 300, 51, 31))
        self.CT1_btn.setFont(font5)
        self.CT1_btn.setStyleSheet(u"background-color: rgb(244, 214, 204);\n"
"color: rgb(0, 0, 0);")
        self.ct1_view = QLabel(self.EnginePage)
        self.ct1_view.setObjectName(u"ct1_view")
        self.ct1_view.setGeometry(QRect(530, 270, 25, 25))
        sizePolicy.setHeightForWidth(self.ct1_view.sizePolicy().hasHeightForWidth())
        self.ct1_view.setSizePolicy(sizePolicy)
        self.ct1_view.setMinimumSize(QSize(25, 25))
        self.ct1_view.setMaximumSize(QSize(25, 25))
        font12 = QFont()
        font12.setFamilies([u"Segoe Script"])
        font12.setPointSize(9)
        self.ct1_view.setFont(font12)
        self.ct1_view.setStyleSheet(u"border-radius:12px;\n"
" border: 2px solid black;\n"
"background-color: rgb(0, 255, 0);\n"
"")
        self.ct2_view = QLabel(self.EnginePage)
        self.ct2_view.setObjectName(u"ct2_view")
        self.ct2_view.setGeometry(QRect(280, 380, 25, 25))
        sizePolicy.setHeightForWidth(self.ct2_view.sizePolicy().hasHeightForWidth())
        self.ct2_view.setSizePolicy(sizePolicy)
        self.ct2_view.setMinimumSize(QSize(25, 25))
        self.ct2_view.setMaximumSize(QSize(25, 25))
        self.ct2_view.setFont(font12)
        self.ct2_view.setStyleSheet(u"border-radius:12px;\n"
" border: 2px solid black;\n"
"background-color: rgb(0, 255, 0);\n"
"")
        self.CT2_btn = QPushButton(self.EnginePage)
        self.CT2_btn.setObjectName(u"CT2_btn")
        self.CT2_btn.setGeometry(QRect(270, 410, 51, 31))
        self.CT2_btn.setFont(font5)
        self.CT2_btn.setStyleSheet(u"background-color: rgb(244, 214, 204);\n"
"color: rgb(0, 0, 0);")
        self.ct3_view = QLabel(self.EnginePage)
        self.ct3_view.setObjectName(u"ct3_view")
        self.ct3_view.setGeometry(QRect(330, 200, 25, 25))
        sizePolicy.setHeightForWidth(self.ct3_view.sizePolicy().hasHeightForWidth())
        self.ct3_view.setSizePolicy(sizePolicy)
        self.ct3_view.setMinimumSize(QSize(25, 25))
        self.ct3_view.setMaximumSize(QSize(25, 25))
        self.ct3_view.setFont(font12)
        self.ct3_view.setStyleSheet(u"border-radius:12px;\n"
" border: 2px solid black;\n"
"background-color: rgb(0, 255, 0);\n"
"")
        self.CT3_btn = QPushButton(self.EnginePage)
        self.CT3_btn.setObjectName(u"CT3_btn")
        self.CT3_btn.setGeometry(QRect(320, 230, 51, 31))
        self.CT3_btn.setFont(font5)
        self.CT3_btn.setStyleSheet(u"background-color: rgb(244, 214, 204);\n"
"color: rgb(0, 0, 0);")
        self.label_3 = QLabel(self.EnginePage)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(270, 520, 331, 41))
        font13 = QFont()
        font13.setFamilies([u"Segoe UI"])
        font13.setPointSize(15)
        font13.setBold(True)
        self.label_3.setFont(font13)
        self.label_3.setStyleSheet(u"color: rgb(156, 196, 178);\n"
"background-color: rgb(50, 55, 59);")
        self.monitorPageBack_btn = QPushButton(self.EnginePage)
        self.monitorPageBack_btn.setObjectName(u"monitorPageBack_btn")
        self.monitorPageBack_btn.setGeometry(QRect(820, 10, 75, 31))
        self.monitorPageBack_btn.setFont(font5)
        self.monitorPageBack_btn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 55, 59);")
        self.label_35 = QLabel(self.EnginePage)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(730, 220, 71, 31))
        font14 = QFont()
        font14.setFamilies([u"Barlow"])
        font14.setPointSize(10)
        font14.setBold(True)
        self.label_35.setFont(font14)
        self.label_35.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_35.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_36 = QLabel(self.EnginePage)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(110, 110, 71, 31))
        self.label_36.setFont(font14)
        self.label_36.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_36.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_37 = QLabel(self.EnginePage)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(390, 480, 71, 31))
        self.label_37.setFont(font14)
        self.label_37.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_37.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.MainStack.addWidget(self.EnginePage)
        self.InferencePage = QWidget()
        self.InferencePage.setObjectName(u"InferencePage")
        self.InferencePage.setStyleSheet(u"QWidget#InferencePage{\n"
"	\n"
"	background-color: rgb(50, 55, 59);\n"
"}")
        self.label_15 = QLabel(self.InferencePage)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(280, 0, 321, 71))
        self.label_15.setFont(font1)
        self.label_15.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.InferencePageBack_btn = QPushButton(self.InferencePage)
        self.InferencePageBack_btn.setObjectName(u"InferencePageBack_btn")
        self.InferencePageBack_btn.setGeometry(QRect(820, 10, 75, 31))
        self.InferencePageBack_btn.setFont(font5)
        self.InferencePageBack_btn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 55, 59);")
        self.label_8 = QLabel(self.InferencePage)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(160, 120, 481, 21))
        self.label_9 = QLabel(self.InferencePage)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(160, 160, 501, 31))
        self.label_10 = QLabel(self.InferencePage)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(230, 140, 49, 16))
        self.infer_list_view = QListWidget(self.InferencePage)
        QListWidgetItem(self.infer_list_view)
        QListWidgetItem(self.infer_list_view)
        QListWidgetItem(self.infer_list_view)
        self.infer_list_view.setObjectName(u"infer_list_view")
        self.infer_list_view.setGeometry(QRect(80, 90, 791, 511))
        self.infer_list_view.setFont(font6)
        self.infer_list_view.setFrameShadow(QFrame.Shadow.Raised)
        self.infer_list_view.setProperty(u"isWrapping", False)
        self.infer_list_view.setLayoutMode(QListView.LayoutMode.SinglePass)
        self.infer_list_view.setSpacing(10)
        self.infer_list_view.setViewMode(QListView.ViewMode.ListMode)
        self.infer_list_view.setUniformItemSizes(False)
        self.infer_list_view.setWordWrap(False)
        self.infer_list_view.setSelectionRectVisible(True)
        self.infer_list_view.setItemAlignment(Qt.AlignmentFlag.AlignLeading)
        self.infer_list_view.setSortingEnabled(True)
        self.MainStack.addWidget(self.InferencePage)
        self.userManagePage = QWidget()
        self.userManagePage.setObjectName(u"userManagePage")
        self.userManagePage.setStyleSheet(u"QWidget#userManagePage{\n"
"	\n"
"	background-color: rgb(50, 55, 59);\n"
"}")
        self.userManage_BackBtn = QPushButton(self.userManagePage)
        self.userManage_BackBtn.setObjectName(u"userManage_BackBtn")
        self.userManage_BackBtn.setGeometry(QRect(820, 20, 75, 31))
        self.userManage_BackBtn.setFont(font5)
        self.userManage_BackBtn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 55, 59);")
        self.label_14 = QLabel(self.userManagePage)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(280, 0, 341, 71))
        self.label_14.setFont(font1)
        self.label_14.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.updateProfileBtn = QPushButton(self.userManagePage)
        self.updateProfileBtn.setObjectName(u"updateProfileBtn")
        self.updateProfileBtn.setGeometry(QRect(580, 70, 161, 41))
        self.ChangePswdBtn = QPushButton(self.userManagePage)
        self.ChangePswdBtn.setObjectName(u"ChangePswdBtn")
        self.ChangePswdBtn.setGeometry(QRect(580, 130, 161, 41))
        self.addUserBtn = QPushButton(self.userManagePage)
        self.addUserBtn.setObjectName(u"addUserBtn")
        self.addUserBtn.setGeometry(QRect(580, 190, 161, 41))
        self.deleteUsrBtn = QPushButton(self.userManagePage)
        self.deleteUsrBtn.setObjectName(u"deleteUsrBtn")
        self.deleteUsrBtn.setGeometry(QRect(580, 250, 161, 41))
        self.changepswdWidget = QWidget(self.userManagePage)
        self.changepswdWidget.setObjectName(u"changepswdWidget")
        self.changepswdWidget.setEnabled(True)
        self.changepswdWidget.setGeometry(QRect(580, 330, 291, 251))
        self.changepswdWidget.setStyleSheet(u"QWidget#changepswdWidget{\n"
"background-color: rgb(74, 88, 89);\n"
"padding: 5 5 5 5;\n"
"}")
        self.changepswdlayout = QVBoxLayout(self.changepswdWidget)
        self.changepswdlayout.setObjectName(u"changepswdlayout")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(10, -1, 5, -1)
        self.label_19 = QLabel(self.changepswdWidget)
        self.label_19.setObjectName(u"label_19")
        font15 = QFont()
        font15.setFamilies([u"Segoe UI"])
        font15.setPointSize(9)
        font15.setBold(False)
        self.label_19.setFont(font15)
        self.label_19.setStyleSheet(u"color: rgb(244, 214, 204);")

        self.horizontalLayout_2.addWidget(self.label_19)

        self.change_cur_pswd_input = QLineEdit(self.changepswdWidget)
        self.change_cur_pswd_input.setObjectName(u"change_cur_pswd_input")
        sizePolicy.setHeightForWidth(self.change_cur_pswd_input.sizePolicy().hasHeightForWidth())
        self.change_cur_pswd_input.setSizePolicy(sizePolicy)
        self.change_cur_pswd_input.setMinimumSize(QSize(152, 0))
        self.change_cur_pswd_input.setMaximumSize(QSize(152, 16777215))
        self.change_cur_pswd_input.setFont(font9)
        self.change_cur_pswd_input.setEchoMode(QLineEdit.EchoMode.Password)

        self.horizontalLayout_2.addWidget(self.change_cur_pswd_input)


        self.changepswdlayout.addLayout(self.horizontalLayout_2)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(10, -1, 5, -1)
        self.label_20 = QLabel(self.changepswdWidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setFont(font15)
        self.label_20.setStyleSheet(u"color: rgb(244, 214, 204);")

        self.horizontalLayout.addWidget(self.label_20)

        self.change_new_pswd_input = QLineEdit(self.changepswdWidget)
        self.change_new_pswd_input.setObjectName(u"change_new_pswd_input")
        sizePolicy.setHeightForWidth(self.change_new_pswd_input.sizePolicy().hasHeightForWidth())
        self.change_new_pswd_input.setSizePolicy(sizePolicy)
        self.change_new_pswd_input.setMinimumSize(QSize(152, 0))
        self.change_new_pswd_input.setMaximumSize(QSize(152, 16777215))
        self.change_new_pswd_input.setFont(font9)
        self.change_new_pswd_input.setEchoMode(QLineEdit.EchoMode.Normal)

        self.horizontalLayout.addWidget(self.change_new_pswd_input)


        self.changepswdlayout.addLayout(self.horizontalLayout)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(10, -1, 5, -1)
        self.label_21 = QLabel(self.changepswdWidget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setFont(font15)
        self.label_21.setStyleSheet(u"color: rgb(244, 214, 204);")

        self.horizontalLayout_3.addWidget(self.label_21)

        self.change_new_pswd_input2 = QLineEdit(self.changepswdWidget)
        self.change_new_pswd_input2.setObjectName(u"change_new_pswd_input2")
        sizePolicy.setHeightForWidth(self.change_new_pswd_input2.sizePolicy().hasHeightForWidth())
        self.change_new_pswd_input2.setSizePolicy(sizePolicy)
        self.change_new_pswd_input2.setMinimumSize(QSize(152, 0))
        self.change_new_pswd_input2.setMaximumSize(QSize(152, 16777215))
        self.change_new_pswd_input2.setFont(font9)
        self.change_new_pswd_input2.setEchoMode(QLineEdit.EchoMode.Normal)

        self.horizontalLayout_3.addWidget(self.change_new_pswd_input2)


        self.changepswdlayout.addLayout(self.horizontalLayout_3)

        self.changepswd_error_label = QLabel(self.changepswdWidget)
        self.changepswd_error_label.setObjectName(u"changepswd_error_label")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.changepswd_error_label.sizePolicy().hasHeightForWidth())
        self.changepswd_error_label.setSizePolicy(sizePolicy1)
        self.changepswd_error_label.setMinimumSize(QSize(0, 20))
        self.changepswd_error_label.setMaximumSize(QSize(1677564, 20))
        font16 = QFont()
        font16.setBold(True)
        self.changepswd_error_label.setFont(font16)
        self.changepswd_error_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.changepswd_error_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.changepswdlayout.addWidget(self.changepswd_error_label)

        self.chg_pswd_btn = QPushButton(self.changepswdWidget)
        self.chg_pswd_btn.setObjectName(u"chg_pswd_btn")
        self.chg_pswd_btn.setMinimumSize(QSize(0, 50))

        self.changepswdlayout.addWidget(self.chg_pswd_btn)

        self.profile = QFrame(self.userManagePage)
        self.profile.setObjectName(u"profile")
        self.profile.setGeometry(QRect(30, 70, 501, 541))
        self.profile.setStyleSheet(u"QWidget#profile{background-color: rgb(200, 62, 77);}")
        self.profile.setFrameShape(QFrame.Shape.StyledPanel)
        self.profile.setFrameShadow(QFrame.Shadow.Raised)
        self.profile_designation_input = QComboBox(self.profile)
        self.profile_designation_input.addItem("")
        self.profile_designation_input.setObjectName(u"profile_designation_input")
        self.profile_designation_input.setGeometry(QRect(130, 260, 191, 31))
        self.label_18 = QLabel(self.profile)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 60, 91, 31))
        self.label_18.setFont(font6)
        self.label_18.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.profile_firstname_input = QLineEdit(self.profile)
        self.profile_firstname_input.setObjectName(u"profile_firstname_input")
        self.profile_firstname_input.setGeometry(QRect(130, 60, 341, 31))
        self.label_23 = QLabel(self.profile)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(30, 110, 91, 31))
        self.label_23.setFont(font6)
        self.label_23.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.profile_lastname_input = QLineEdit(self.profile)
        self.profile_lastname_input.setObjectName(u"profile_lastname_input")
        self.profile_lastname_input.setGeometry(QRect(130, 110, 341, 31))
        self.label_24 = QLabel(self.profile)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(30, 160, 91, 31))
        self.label_24.setFont(font6)
        self.label_24.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.profile_DOB_input = QLineEdit(self.profile)
        self.profile_DOB_input.setObjectName(u"profile_DOB_input")
        self.profile_DOB_input.setGeometry(QRect(130, 160, 341, 31))
        self.label_25 = QLabel(self.profile)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(30, 260, 91, 31))
        self.label_25.setFont(font6)
        self.label_25.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_26 = QLabel(self.profile)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(30, 310, 91, 31))
        self.label_26.setFont(font6)
        self.label_26.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.profile_level_input = QComboBox(self.profile)
        self.profile_level_input.addItem("")
        self.profile_level_input.setObjectName(u"profile_level_input")
        self.profile_level_input.setGeometry(QRect(130, 310, 191, 31))
        self.label_27 = QLabel(self.profile)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(30, 360, 91, 31))
        self.label_27.setFont(font6)
        self.label_27.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.profile_phone_input = QLineEdit(self.profile)
        self.profile_phone_input.setObjectName(u"profile_phone_input")
        self.profile_phone_input.setGeometry(QRect(130, 360, 341, 31))
        self.label_28 = QLabel(self.profile)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(30, 410, 91, 31))
        self.label_28.setFont(font6)
        self.label_28.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.profile_email_input = QLineEdit(self.profile)
        self.profile_email_input.setObjectName(u"profile_email_input")
        self.profile_email_input.setGeometry(QRect(130, 410, 341, 31))
        self.label_29 = QLabel(self.profile)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(30, 460, 91, 31))
        self.label_29.setFont(font6)
        self.label_29.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.profile_id_input = QLineEdit(self.profile)
        self.profile_id_input.setObjectName(u"profile_id_input")
        self.profile_id_input.setGeometry(QRect(130, 460, 341, 31))
        self.label_30 = QLabel(self.profile)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(30, 210, 91, 31))
        self.label_30.setFont(font6)
        self.label_30.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.profile_gender_input = QComboBox(self.profile)
        self.profile_gender_input.addItem("")
        self.profile_gender_input.setObjectName(u"profile_gender_input")
        self.profile_gender_input.setGeometry(QRect(130, 210, 191, 31))
        self.label_22 = QLabel(self.profile)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(30, 10, 91, 31))
        self.label_22.setFont(font6)
        self.label_22.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.profile_usderid_input = QLineEdit(self.profile)
        self.profile_usderid_input.setObjectName(u"profile_usderid_input")
        self.profile_usderid_input.setGeometry(QRect(130, 10, 261, 31))
        self.profile_Btn = QPushButton(self.profile)
        self.profile_Btn.setObjectName(u"profile_Btn")
        self.profile_Btn.setGeometry(QRect(370, 500, 101, 31))
        self.profile_error_label = QLabel(self.profile)
        self.profile_error_label.setObjectName(u"profile_error_label")
        self.profile_error_label.setGeometry(QRect(30, 510, 311, 16))
        self.profile_error_label.setFont(font16)
        self.profile_error_label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.profile_error_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.profile_search_btn = QPushButton(self.profile)
        self.profile_search_btn.setObjectName(u"profile_search_btn")
        self.profile_search_btn.setGeometry(QRect(400, 10, 71, 31))
        self.MainStack.addWidget(self.userManagePage)
        self.AIModelsPage = QWidget()
        self.AIModelsPage.setObjectName(u"AIModelsPage")
        self.AIModelsPage.setStyleSheet(u"QWidget#AIModelsPage{background-color: rgb(200, 62, 77);}")
        self.label_31 = QLabel(self.AIModelsPage)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(280, 0, 371, 71))
        self.label_31.setFont(font1)
        self.label_31.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.aimodels_backBtn = QPushButton(self.AIModelsPage)
        self.aimodels_backBtn.setObjectName(u"aimodels_backBtn")
        self.aimodels_backBtn.setGeometry(QRect(820, 10, 75, 31))
        self.aimodels_backBtn.setFont(font5)
        self.aimodels_backBtn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 55, 59);")
        self.label_117 = QLabel(self.AIModelsPage)
        self.label_117.setObjectName(u"label_117")
        self.label_117.setGeometry(QRect(20, 90, 221, 31))
        font17 = QFont()
        font17.setFamilies([u"Barlow"])
        font17.setPointSize(18)
        font17.setBold(True)
        self.label_117.setFont(font17)
        self.label_117.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_162 = QLabel(self.AIModelsPage)
        self.label_162.setObjectName(u"label_162")
        self.label_162.setGeometry(QRect(40, 130, 121, 31))
        font18 = QFont()
        font18.setFamilies([u"Arial"])
        font18.setPointSize(12)
        font18.setBold(True)
        self.label_162.setFont(font18)
        self.label_162.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.detector_model_label = QLabel(self.AIModelsPage)
        self.detector_model_label.setObjectName(u"detector_model_label")
        self.detector_model_label.setGeometry(QRect(170, 130, 391, 31))
        self.detector_model_label.setFont(font6)
        self.detector_model_label.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.detector_model_label.setMargin(5)
        self.detector_model_btn = QPushButton(self.AIModelsPage)
        self.detector_model_btn.setObjectName(u"detector_model_btn")
        self.detector_model_btn.setGeometry(QRect(580, 130, 111, 31))
        font19 = QFont()
        font19.setFamilies([u"Segoe UI"])
        font19.setPointSize(11)
        self.detector_model_btn.setFont(font19)
        self.detector_model_btn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 55, 59);")
        self.label_164 = QLabel(self.AIModelsPage)
        self.label_164.setObjectName(u"label_164")
        self.label_164.setGeometry(QRect(40, 170, 121, 31))
        self.label_164.setFont(font18)
        self.label_164.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.detector_proto_btn = QPushButton(self.AIModelsPage)
        self.detector_proto_btn.setObjectName(u"detector_proto_btn")
        self.detector_proto_btn.setGeometry(QRect(580, 170, 111, 31))
        self.detector_proto_btn.setFont(font19)
        self.detector_proto_btn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 55, 59);")
        self.detector_proto_label = QLabel(self.AIModelsPage)
        self.detector_proto_label.setObjectName(u"detector_proto_label")
        self.detector_proto_label.setGeometry(QRect(170, 170, 391, 31))
        self.detector_proto_label.setFont(font6)
        self.detector_proto_label.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.detector_proto_label.setMargin(5)
        self.label_166 = QLabel(self.AIModelsPage)
        self.label_166.setObjectName(u"label_166")
        self.label_166.setGeometry(QRect(40, 250, 121, 31))
        self.label_166.setFont(font18)
        self.label_166.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.class_model_label = QLabel(self.AIModelsPage)
        self.class_model_label.setObjectName(u"class_model_label")
        self.class_model_label.setGeometry(QRect(170, 250, 391, 31))
        self.class_model_label.setFont(font6)
        self.class_model_label.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.class_model_label.setMargin(5)
        self.classifier_model_btn = QPushButton(self.AIModelsPage)
        self.classifier_model_btn.setObjectName(u"classifier_model_btn")
        self.classifier_model_btn.setGeometry(QRect(580, 250, 111, 31))
        self.classifier_model_btn.setFont(font19)
        self.classifier_model_btn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 55, 59);")
        self.label_168 = QLabel(self.AIModelsPage)
        self.label_168.setObjectName(u"label_168")
        self.label_168.setGeometry(QRect(20, 210, 221, 31))
        self.label_168.setFont(font17)
        self.label_168.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.behaviour_btn = QPushButton(self.AIModelsPage)
        self.behaviour_btn.setObjectName(u"behaviour_btn")
        self.behaviour_btn.setGeometry(QRect(580, 410, 111, 31))
        self.behaviour_btn.setFont(font19)
        self.behaviour_btn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 55, 59);")
        self.behaviour_label = QLabel(self.AIModelsPage)
        self.behaviour_label.setObjectName(u"behaviour_label")
        self.behaviour_label.setGeometry(QRect(170, 410, 391, 31))
        self.behaviour_label.setFont(font6)
        self.behaviour_label.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.behaviour_label.setMargin(5)
        self.label_221 = QLabel(self.AIModelsPage)
        self.label_221.setObjectName(u"label_221")
        self.label_221.setGeometry(QRect(40, 410, 121, 31))
        self.label_221.setFont(font18)
        self.label_221.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_222 = QLabel(self.AIModelsPage)
        self.label_222.setObjectName(u"label_222")
        self.label_222.setGeometry(QRect(20, 380, 221, 31))
        font20 = QFont()
        font20.setFamilies([u"Barlow"])
        font20.setPointSize(14)
        font20.setBold(True)
        self.label_222.setFont(font20)
        self.label_222.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_223 = QLabel(self.AIModelsPage)
        self.label_223.setObjectName(u"label_223")
        self.label_223.setGeometry(QRect(40, 290, 121, 31))
        self.label_223.setFont(font18)
        self.label_223.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.classifier_proto_btn = QPushButton(self.AIModelsPage)
        self.classifier_proto_btn.setObjectName(u"classifier_proto_btn")
        self.classifier_proto_btn.setGeometry(QRect(580, 290, 111, 31))
        self.classifier_proto_btn.setFont(font19)
        self.classifier_proto_btn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 55, 59);")
        self.class_proto_label = QLabel(self.AIModelsPage)
        self.class_proto_label.setObjectName(u"class_proto_label")
        self.class_proto_label.setGeometry(QRect(170, 290, 391, 31))
        self.class_proto_label.setFont(font6)
        self.class_proto_label.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.class_proto_label.setMargin(5)
        self.label_225 = QLabel(self.AIModelsPage)
        self.label_225.setObjectName(u"label_225")
        self.label_225.setGeometry(QRect(20, 320, 371, 61))
        font21 = QFont()
        font21.setFamilies([u"Barlow"])
        font21.setPointSize(25)
        font21.setBold(True)
        font21.setItalic(False)
        font21.setUnderline(False)
        font21.setStrikeOut(False)
        self.label_225.setFont(font21)
        self.label_225.setStyleSheet(u"color: rgb(0, 85, 127);")
        self.relationship_btn = QPushButton(self.AIModelsPage)
        self.relationship_btn.setObjectName(u"relationship_btn")
        self.relationship_btn.setGeometry(QRect(580, 570, 111, 31))
        self.relationship_btn.setFont(font19)
        self.relationship_btn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 55, 59);")
        self.label_226 = QLabel(self.AIModelsPage)
        self.label_226.setObjectName(u"label_226")
        self.label_226.setGeometry(QRect(40, 570, 121, 31))
        self.label_226.setFont(font18)
        self.label_226.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_227 = QLabel(self.AIModelsPage)
        self.label_227.setObjectName(u"label_227")
        self.label_227.setGeometry(QRect(20, 540, 221, 31))
        self.label_227.setFont(font20)
        self.label_227.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.relation_label = QLabel(self.AIModelsPage)
        self.relation_label.setObjectName(u"relation_label")
        self.relation_label.setGeometry(QRect(170, 570, 391, 31))
        self.relation_label.setFont(font6)
        self.relation_label.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.relation_label.setMargin(5)
        self.disease_btn = QPushButton(self.AIModelsPage)
        self.disease_btn.setObjectName(u"disease_btn")
        self.disease_btn.setGeometry(QRect(580, 490, 111, 31))
        self.disease_btn.setFont(font19)
        self.disease_btn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 55, 59);")
        self.label_229 = QLabel(self.AIModelsPage)
        self.label_229.setObjectName(u"label_229")
        self.label_229.setGeometry(QRect(20, 460, 221, 31))
        self.label_229.setFont(font20)
        self.label_229.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.diesese_label = QLabel(self.AIModelsPage)
        self.diesese_label.setObjectName(u"diesese_label")
        self.diesese_label.setGeometry(QRect(170, 490, 391, 31))
        self.diesese_label.setFont(font6)
        self.diesese_label.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.diesese_label.setMargin(5)
        self.label_231 = QLabel(self.AIModelsPage)
        self.label_231.setObjectName(u"label_231")
        self.label_231.setGeometry(QRect(40, 490, 121, 31))
        self.label_231.setFont(font18)
        self.label_231.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_232 = QLabel(self.AIModelsPage)
        self.label_232.setObjectName(u"label_232")
        self.label_232.setGeometry(QRect(20, 30, 261, 61))
        self.label_232.setFont(font21)
        self.label_232.setStyleSheet(u"\n"
"color: rgb(0, 85, 127);")
        self.models_save_btn = QPushButton(self.AIModelsPage)
        self.models_save_btn.setObjectName(u"models_save_btn")
        self.models_save_btn.setGeometry(QRect(700, 80, 141, 31))
        self.MainStack.addWidget(self.AIModelsPage)
        self.settingsPage = QWidget()
        self.settingsPage.setObjectName(u"settingsPage")
        self.settingsPage.setStyleSheet(u"QWidget#settingsPage{\n"
"	\n"
"	background-color: rgb(50, 55, 59);\n"
"}")
        self.settingsPage_backBtn = QPushButton(self.settingsPage)
        self.settingsPage_backBtn.setObjectName(u"settingsPage_backBtn")
        self.settingsPage_backBtn.setGeometry(QRect(820, 10, 75, 31))
        self.settingsPage_backBtn.setFont(font5)
        self.settingsPage_backBtn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 55, 59);")
        self.label_32 = QLabel(self.settingsPage)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(280, 0, 391, 71))
        self.label_32.setFont(font1)
        self.label_32.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_33 = QLabel(self.settingsPage)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(30, 80, 191, 31))
        self.label_33.setFont(font8)
        self.label_33.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_34 = QLabel(self.settingsPage)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(50, 130, 121, 31))
        self.label_34.setFont(font18)
        self.label_34.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.trap1_path_btn = QPushButton(self.settingsPage)
        self.trap1_path_btn.setObjectName(u"trap1_path_btn")
        self.trap1_path_btn.setGeometry(QRect(590, 130, 111, 31))
        self.trap1_path_btn.setFont(font19)
        self.trap1_path_btn.setStyleSheet(u"background-color: rgb(200, 62, 77);\n"
"color: rgb(255, 255, 255)")
        self.trap1_path_label = QLabel(self.settingsPage)
        self.trap1_path_label.setObjectName(u"trap1_path_label")
        self.trap1_path_label.setGeometry(QRect(180, 130, 391, 31))
        self.trap1_path_label.setFont(font9)
        self.trap1_path_label.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.trap1_path_label.setMargin(5)
        self.label_71 = QLabel(self.settingsPage)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(50, 190, 121, 31))
        self.label_71.setFont(font18)
        self.label_71.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.trap2_path_label = QLabel(self.settingsPage)
        self.trap2_path_label.setObjectName(u"trap2_path_label")
        self.trap2_path_label.setGeometry(QRect(180, 190, 391, 31))
        self.trap2_path_label.setFont(font9)
        self.trap2_path_label.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.trap2_path_label.setMargin(5)
        self.trap2_path_btn = QPushButton(self.settingsPage)
        self.trap2_path_btn.setObjectName(u"trap2_path_btn")
        self.trap2_path_btn.setGeometry(QRect(590, 190, 111, 31))
        self.trap2_path_btn.setFont(font19)
        self.trap2_path_btn.setStyleSheet(u"background-color: rgb(200, 62, 77);\n"
"color: rgb(255, 255, 255)")
        self.label_73 = QLabel(self.settingsPage)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(50, 250, 121, 31))
        self.label_73.setFont(font18)
        self.label_73.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.trap3_path_label = QLabel(self.settingsPage)
        self.trap3_path_label.setObjectName(u"trap3_path_label")
        self.trap3_path_label.setGeometry(QRect(180, 250, 391, 31))
        self.trap3_path_label.setFont(font9)
        self.trap3_path_label.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.trap3_path_label.setMargin(5)
        self.trap3_path_btn = QPushButton(self.settingsPage)
        self.trap3_path_btn.setObjectName(u"trap3_path_btn")
        self.trap3_path_btn.setGeometry(QRect(590, 250, 111, 31))
        self.trap3_path_btn.setFont(font19)
        self.trap3_path_btn.setStyleSheet(u"background-color: rgb(200, 62, 77);\n"
"color: rgb(255, 255, 255)")
        self.label_75 = QLabel(self.settingsPage)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(30, 320, 211, 31))
        self.label_75.setFont(font8)
        self.label_75.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_116 = QLabel(self.settingsPage)
        self.label_116.setObjectName(u"label_116")
        self.label_116.setGeometry(QRect(50, 370, 171, 31))
        self.label_116.setFont(font18)
        self.label_116.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.rules_path_label = QLabel(self.settingsPage)
        self.rules_path_label.setObjectName(u"rules_path_label")
        self.rules_path_label.setGeometry(QRect(230, 430, 391, 31))
        self.rules_path_label.setFont(font9)
        self.rules_path_label.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.rules_path_label.setMargin(5)
        self.label_161 = QLabel(self.settingsPage)
        self.label_161.setObjectName(u"label_161")
        self.label_161.setGeometry(QRect(50, 430, 171, 31))
        self.label_161.setFont(font18)
        self.label_161.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.rules_path_btn = QPushButton(self.settingsPage)
        self.rules_path_btn.setObjectName(u"rules_path_btn")
        self.rules_path_btn.setGeometry(QRect(640, 430, 131, 31))
        self.rules_path_btn.setFont(font19)
        self.rules_path_btn.setStyleSheet(u"background-color: rgb(200, 62, 77);\n"
"color: rgb(255, 255, 255)")
        self.target_speces_name = QLineEdit(self.settingsPage)
        self.target_speces_name.setObjectName(u"target_speces_name")
        self.target_speces_name.setGeometry(QRect(230, 370, 341, 31))
        self.target_speces_name.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.settings_save_btn = QPushButton(self.settingsPage)
        self.settings_save_btn.setObjectName(u"settings_save_btn")
        self.settings_save_btn.setGeometry(QRect(740, 80, 141, 31))
        self.MainStack.addWidget(self.settingsPage)
        self.helpPage = QWidget()
        self.helpPage.setObjectName(u"helpPage")
        self.helpPage.setStyleSheet(u"QWidget#helpPage{background-color: rgb(200, 62, 77);}")
        self.helpPage_back_btn = QPushButton(self.helpPage)
        self.helpPage_back_btn.setObjectName(u"helpPage_back_btn")
        self.helpPage_back_btn.setGeometry(QRect(820, 10, 75, 31))
        self.helpPage_back_btn.setFont(font5)
        self.helpPage_back_btn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 55, 59);")
        self.label_38 = QLabel(self.helpPage)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(410, 0, 81, 71))
        self.label_38.setFont(font1)
        self.label_38.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.textBrowser = QTextBrowser(self.helpPage)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(20, 70, 861, 541))
        self.MainStack.addWidget(self.helpPage)
        self.analysisPage = QWidget()
        self.analysisPage.setObjectName(u"analysisPage")
        self.analysisPage.setStyleSheet(u"QWidget#analysisPage{\n"
"	\n"
"	background-color: rgb(50, 55, 59);\n"
"}")
        self.analysisPage_back_btn = QPushButton(self.analysisPage)
        self.analysisPage_back_btn.setObjectName(u"analysisPage_back_btn")
        self.analysisPage_back_btn.setGeometry(QRect(820, 10, 75, 31))
        self.analysisPage_back_btn.setFont(font5)
        self.analysisPage_back_btn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 55, 59);")
        self.label_39 = QLabel(self.analysisPage)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(280, 0, 391, 71))
        self.label_39.setFont(font1)
        self.label_39.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_40 = QLabel(self.analysisPage)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(100, 90, 691, 461))
        self.label_40.setStyleSheet(u"border-image: url(:/AppResources/graph.png);")
        self.MainStack.addWidget(self.analysisPage)
        AppUI.setCentralWidget(self.Main)
        self.statusbar = QStatusBar(AppUI)
        self.statusbar.setObjectName(u"statusbar")
        AppUI.setStatusBar(self.statusbar)

        self.retranslateUi(AppUI)

        self.MainStack.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(AppUI)
    # setupUi

    def retranslateUi(self, AppUI):
        AppUI.setWindowTitle(QCoreApplication.translate("AppUI", u"WildLife App", None))
        self.label.setText(QCoreApplication.translate("AppUI", u"Wildlife Conservation Application", None))
        self.label.adjustSize()
        self.Db_monitor_btn.setText(QCoreApplication.translate("AppUI", u"Monitoring Panel", None))
        self.profile_label.setText("")
        self.username_label.setText(QCoreApplication.translate("AppUI", u"User1", None))
        self.Db_Logout_btn.setText(QCoreApplication.translate("AppUI", u"Logout", None))
        self.Db_inference_btn.setText(QCoreApplication.translate("AppUI", u"Inference", None))
        self.Db_analysis_btn.setText(QCoreApplication.translate("AppUI", u"Analysis Report", None))
        self.Db_help_btn.setText(QCoreApplication.translate("AppUI", u"Help", None))
        self.Db_aboutus_btn.setText(QCoreApplication.translate("AppUI", u"About Us", None))
        self.Db_settings_btn.setText(QCoreApplication.translate("AppUI", u"Settings", None))
        self.Db_Alert_btn.setText(QCoreApplication.translate("AppUI", u"Alert Team", None))
        self.Db_models_btn.setText(QCoreApplication.translate("AppUI", u"Configure AI Models", None))
        self.Db_management_btn.setText(QCoreApplication.translate("AppUI", u"User Management", None))
        self.DB_error_label.setText("")
        self.label_11.setText(QCoreApplication.translate("AppUI", u"Alert Panel", None))
        self.label_11.adjustSize()
        self.alertpage_back_btn.setText(QCoreApplication.translate("AppUI", u"Back", None))
        self.label_12.setText(QCoreApplication.translate("AppUI", u"Send Alert To: ", None))
        self.alert_team_input.setItemText(0, QCoreApplication.translate("AppUI", u"Choose", None))
        self.alert_team_input.setItemText(1, QCoreApplication.translate("AppUI", u"Zone 1: Team A", None))
        self.alert_team_input.setItemText(2, QCoreApplication.translate("AppUI", u"Zone 1: Team B", None))
        self.alert_team_input.setItemText(3, QCoreApplication.translate("AppUI", u"Zone 2: Team A", None))
        self.alert_team_input.setItemText(4, QCoreApplication.translate("AppUI", u"Zone 2: Team B", None))
        self.alert_team_input.setItemText(5, QCoreApplication.translate("AppUI", u"Zone 2: Team C", None))
        self.alert_team_input.setItemText(6, QCoreApplication.translate("AppUI", u"Zone 3: Team A", None))
        self.alert_team_input.setItemText(7, QCoreApplication.translate("AppUI", u"Zone 3: Team B", None))

        self.label_13.setText(QCoreApplication.translate("AppUI", u"Title:", None))
        self.label_16.setText(QCoreApplication.translate("AppUI", u"Details:", None))
        self.alert_send_btn.setText(QCoreApplication.translate("AppUI", u"Send", None))
        self.alert_error_label.setText("")
        self.label_4.setText("")
        self.label_5.setText(QCoreApplication.translate("AppUI", u"Login", None))
        self.label_6.setText(QCoreApplication.translate("AppUI", u"UserID: ", None))
        self.label_7.setText(QCoreApplication.translate("AppUI", u"Password: ", None))
        self.loginbtn.setText(QCoreApplication.translate("AppUI", u"Login", None))
        self.login_error_label.setText("")
        self.aboutus_back_btn.setText(QCoreApplication.translate("AppUI", u"Back", None))
        self.label_17.setText(QCoreApplication.translate("AppUI", u"<label>\n"
"  <h2>About Us</h2>\n"
"  <p>\n"
"    Welcome to our final year project, <strong>Wildlife Conservation Using Deep Learning</strong>. \n"
"    Our goal is to leverage cutting-edge deep learning technologies to support and enhance efforts in \n"
"    wildlife conservation, enabling better monitoring, analysis, and protection of endangered species \n"
"    and their habitats.\n"
"  </p>\n"
"  <p>\n"
"    This project is a collaborative effort by a passionate group of engineering students from Srinivas University Mangalore, \n"
"    Department of Computer Science. Our team members:\n"
"  </p>\n"
"  <ul>\n"
"    <li>Vinayak - 1SU22CS715</li>\n"
"    <li>Shivakumar - 1SU22CS716</li>\n"
"    <li>Akshata Shivakumar Hiremath - 1SU22CS717</li>\n"
"    <li>Zoeb Mustakahmed Dindoor - 1SU22CS719</li>\n"
"  </ul>\n"
"  <p>\n"
"    We are dedicated to contributing towards a sustainable future by integrating technology and nature conservation. \n"
"    Thank you for your interest in our project.\n"
"  </p>\n"
""
                        "</label>", None))
        self.label_2.setText(QCoreApplication.translate("AppUI", u"Monitoring Panel", None))
        self.label_2.adjustSize()
        self.ForestMapView.setText("")
        self.CT1_btn.setText(QCoreApplication.translate("AppUI", u"Trap 1", None))
        self.ct1_view.setText("")
        self.ct2_view.setText("")
        self.CT2_btn.setText(QCoreApplication.translate("AppUI", u"Trap 2", None))
        self.ct3_view.setText("")
        self.CT3_btn.setText(QCoreApplication.translate("AppUI", u"Trap 3", None))
        self.label_3.setText(QCoreApplication.translate("AppUI", u"  Forest Area Live Monitor..", None))
        self.monitorPageBack_btn.setText(QCoreApplication.translate("AppUI", u"Back", None))
        self.label_35.setText(QCoreApplication.translate("AppUI", u"ZONE 1", None))
        self.label_36.setText(QCoreApplication.translate("AppUI", u"ZONE 3", None))
        self.label_37.setText(QCoreApplication.translate("AppUI", u"ZONE 2", None))
        self.label_15.setText(QCoreApplication.translate("AppUI", u"Inference", None))
        self.label_15.adjustSize()
        self.InferencePageBack_btn.setText(QCoreApplication.translate("AppUI", u"Back", None))
        self.label_8.setText(QCoreApplication.translate("AppUI", u"2 Mountain Leopards Detected in Zone 3 at 29/11/2025:23:56 IST", None))
        self.label_9.setText(QCoreApplication.translate("AppUI", u"Squirel Species Behavior Classification: Nut Consumption in Zone 2 at 30/11/2025:05:56 IST", None))
        self.label_10.setText(QCoreApplication.translate("AppUI", u"TextLabel", None))

        __sortingEnabled = self.infer_list_view.isSortingEnabled()
        self.infer_list_view.setSortingEnabled(False)
        ___qlistwidgetitem = self.infer_list_view.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("AppUI", u"Behavior Detector: Squirell Consumed Nuts Detected in Zone 1 at 11/01/2025 - 13:45:65 IST", None));
        ___qlistwidgetitem1 = self.infer_list_view.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("AppUI", u"Disease Detector: Black Buck With Anterior Stomach Wound Detected at 05/01/2025 - 14:34:54 IST", None));
        ___qlistwidgetitem2 = self.infer_list_view.item(2)
        ___qlistwidgetitem2.setText(QCoreApplication.translate("AppUI", u"Species Detector: 2 Mountain Leopards Detected in Zone 3 at 12/01/2025 - 06:56:45 IST", None));
        self.infer_list_view.setSortingEnabled(__sortingEnabled)

        self.userManage_BackBtn.setText(QCoreApplication.translate("AppUI", u"Back", None))
        self.label_14.setText(QCoreApplication.translate("AppUI", u"User Management", None))
        self.label_14.adjustSize()
        self.updateProfileBtn.setText(QCoreApplication.translate("AppUI", u"Update Profile", None))
        self.ChangePswdBtn.setText(QCoreApplication.translate("AppUI", u"Change Password", None))
        self.addUserBtn.setText(QCoreApplication.translate("AppUI", u"Add User", None))
        self.deleteUsrBtn.setText(QCoreApplication.translate("AppUI", u"Delete User", None))
        self.label_19.setText(QCoreApplication.translate("AppUI", u"Current Password: ", None))
        self.label_20.setText(QCoreApplication.translate("AppUI", u"New Password: ", None))
        self.label_21.setText(QCoreApplication.translate("AppUI", u"Repeat Password: ", None))
        self.changepswd_error_label.setText("")
        self.chg_pswd_btn.setText(QCoreApplication.translate("AppUI", u"Update Password", None))
        self.profile_designation_input.setItemText(0, QCoreApplication.translate("AppUI", u"Choose", None))

        self.label_18.setText(QCoreApplication.translate("AppUI", u"First Name: ", None))
        self.profile_firstname_input.setText("")
        self.label_23.setText(QCoreApplication.translate("AppUI", u"Last Name: ", None))
        self.profile_lastname_input.setText("")
        self.label_24.setText(QCoreApplication.translate("AppUI", u"DOB: ", None))
        self.profile_DOB_input.setText("")
        self.label_25.setText(QCoreApplication.translate("AppUI", u"Designation: ", None))
        self.label_26.setText(QCoreApplication.translate("AppUI", u"Level: ", None))
        self.profile_level_input.setItemText(0, QCoreApplication.translate("AppUI", u"Choose", None))

        self.label_27.setText(QCoreApplication.translate("AppUI", u"Phone No. : ", None))
        self.profile_phone_input.setText("")
        self.label_28.setText(QCoreApplication.translate("AppUI", u"EmailID: ", None))
        self.profile_email_input.setText("")
        self.label_29.setText(QCoreApplication.translate("AppUI", u"Institute ID: ", None))
        self.profile_id_input.setText("")
        self.label_30.setText(QCoreApplication.translate("AppUI", u"Gender: ", None))
        self.profile_gender_input.setItemText(0, QCoreApplication.translate("AppUI", u"Choose", None))

        self.label_22.setText(QCoreApplication.translate("AppUI", u"UserID: ", None))
        self.profile_usderid_input.setText("")
        self.profile_Btn.setText(QCoreApplication.translate("AppUI", u"Update", None))
        self.profile_error_label.setText("")
        self.profile_search_btn.setText(QCoreApplication.translate("AppUI", u"Search", None))
        self.label_31.setText(QCoreApplication.translate("AppUI", u"Configure AI Models", None))
        self.label_31.adjustSize()
        self.aimodels_backBtn.setText(QCoreApplication.translate("AppUI", u"Back", None))
        self.label_117.setText(QCoreApplication.translate("AppUI", u"Detector: ", None))
        self.label_162.setText(QCoreApplication.translate("AppUI", u"Model: ", None))
        self.detector_model_label.setText(QCoreApplication.translate("AppUI", u"/home/shadab/bruh.mp4", None))
        self.detector_model_btn.setText(QCoreApplication.translate("AppUI", u"Select", None))
        self.label_164.setText(QCoreApplication.translate("AppUI", u"Model Proto: ", None))
        self.detector_proto_btn.setText(QCoreApplication.translate("AppUI", u"Select", None))
        self.detector_proto_label.setText(QCoreApplication.translate("AppUI", u"/home/shadab/bruh.mp4", None))
        self.label_166.setText(QCoreApplication.translate("AppUI", u"Model: ", None))
        self.class_model_label.setText(QCoreApplication.translate("AppUI", u"/home/shadab/bruh.mp4", None))
        self.classifier_model_btn.setText(QCoreApplication.translate("AppUI", u"Select", None))
        self.label_168.setText(QCoreApplication.translate("AppUI", u"Classifier: ", None))
        self.behaviour_btn.setText(QCoreApplication.translate("AppUI", u"Select", None))
        self.behaviour_label.setText(QCoreApplication.translate("AppUI", u"/home/shadab/bruh.mp4", None))
        self.label_221.setText(QCoreApplication.translate("AppUI", u"Model: ", None))
        self.label_222.setText(QCoreApplication.translate("AppUI", u"Behaviour Models: ", None))
        self.label_223.setText(QCoreApplication.translate("AppUI", u"Model Proto: ", None))
        self.classifier_proto_btn.setText(QCoreApplication.translate("AppUI", u"Select", None))
        self.class_proto_label.setText(QCoreApplication.translate("AppUI", u"/home/shadab/bruh.mp4", None))
        self.label_225.setText(QCoreApplication.translate("AppUI", u"Advanced Models:", None))
        self.relationship_btn.setText(QCoreApplication.translate("AppUI", u"Select", None))
        self.label_226.setText(QCoreApplication.translate("AppUI", u"Model: ", None))
        self.label_227.setText(QCoreApplication.translate("AppUI", u"Relationship Model: ", None))
        self.relation_label.setText(QCoreApplication.translate("AppUI", u"Relationship Model: ", None))
        self.disease_btn.setText(QCoreApplication.translate("AppUI", u"Select", None))
        self.label_229.setText(QCoreApplication.translate("AppUI", u"Disease Models: ", None))
        self.diesese_label.setText(QCoreApplication.translate("AppUI", u"Relationship Model: ", None))
        self.label_231.setText(QCoreApplication.translate("AppUI", u"Model: ", None))
        self.label_232.setText(QCoreApplication.translate("AppUI", u"Basic Models", None))
        self.models_save_btn.setText(QCoreApplication.translate("AppUI", u"Save", None))
        self.settingsPage_backBtn.setText(QCoreApplication.translate("AppUI", u"Back", None))
        self.label_32.setText(QCoreApplication.translate("AppUI", u"Application Settings", None))
        self.label_32.adjustSize()
        self.label_33.setText(QCoreApplication.translate("AppUI", u"Cameras:", None))
        self.label_34.setText(QCoreApplication.translate("AppUI", u"Camera Trap1 : ", None))
        self.trap1_path_btn.setText(QCoreApplication.translate("AppUI", u"Select Camera", None))
        self.trap1_path_label.setText(QCoreApplication.translate("AppUI", u"/home/shadab/bruh.mp4", None))
        self.label_71.setText(QCoreApplication.translate("AppUI", u"Camera Trap2 : ", None))
        self.trap2_path_label.setText(QCoreApplication.translate("AppUI", u"Camera Trap2 : ", None))
        self.trap2_path_btn.setText(QCoreApplication.translate("AppUI", u"Select Camera", None))
        self.label_73.setText(QCoreApplication.translate("AppUI", u"Camera Trap3 : ", None))
        self.trap3_path_label.setText(QCoreApplication.translate("AppUI", u"/home/shadab/bruh.mp4", None))
        self.trap3_path_btn.setText(QCoreApplication.translate("AppUI", u"Select Camera", None))
        self.label_75.setText(QCoreApplication.translate("AppUI", u"Engine Settings: ", None))
        self.label_116.setText(QCoreApplication.translate("AppUI", u"Target Species Name: ", None))
        self.rules_path_label.setText(QCoreApplication.translate("AppUI", u"Rules: ", None))
        self.label_161.setText(QCoreApplication.translate("AppUI", u"Rules: ", None))
        self.rules_path_btn.setText(QCoreApplication.translate("AppUI", u"Browse Rules File", None))
        self.target_speces_name.setText(QCoreApplication.translate("AppUI", u"BRUHH", None))
        self.settings_save_btn.setText(QCoreApplication.translate("AppUI", u"Save", None))
        self.helpPage_back_btn.setText(QCoreApplication.translate("AppUI", u"Back", None))
        self.label_38.setText(QCoreApplication.translate("AppUI", u"Help", None))
        self.label_38.adjustSize()
        self.textBrowser.setHtml(QCoreApplication.translate("AppUI", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:700;\">1. Monitor: Real-Time Camera Traps Preview &amp; Model Predictions </span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Purpose:</span> The <span style=\" font-style:italic;\">Monitor</span> page allows users to view real-time "
                        "video feeds from camera traps deployed in wildlife areas. This is essential for monitoring wildlife behavior and activities. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Key Features:</span> </p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Live Camera Feeds:</span> Watch camera traps in action, with a preview of the footage captured from various locations. </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Model Predictions:</span> Based on the camera footage, AI models predict species, behavior, and other relevant data. These predictions can be immedia"
                        "tely viewed alongside the live feed. </li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Use Case:</span> If you're monitoring a wildlife area, this feature helps you detect species activity in real-time. </li></ul>\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:700;\">2. Inference: View &amp; Analyze Model Results </span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Purpose:</span> The <span style=\" font-style:italic;\">Inference</span> page allows you to view detailed results of model predictions and analyses performed on the captured camera data. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-in"
                        "dent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Key Features:</span> </p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Inference Results:</span> View the specific output of model analyses, such as species identification, behavioral patterns, and any other critical findings. </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Decision Making:</span> The results enable quick decision-making by scientists and forest teams to take necessary actions or interventions based on the insights. </li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Use Case:</sp"
                        "an> If a rare or endangered species is detected, the relevant team can review the prediction and take action accordingly. </li></ul>\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:700;\">3. Alert: Notify the Forest Team for Immediate Action </span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Purpose:</span> The <span style=\" font-style:italic;\">Alert</span> page serves as an emergency or action-triggering mechanism to notify the concerned forest team of any urgent or important events. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Key Features:</span> </p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -q"
                        "t-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Alert Notification:</span> If significant data or findings (e.g., detection of illegal activity, rare species sightings) are identified, the system automatically generates alerts. </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Access Control:</span> Only accessible by Senior Scientists or Supervisors, ensuring that only authorized personnel can issue alerts. </li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Use Case:</span> If there is an illegal poaching attempt or a critical observation, an alert is sent to the forest team to initiate decisive action. </li></ul>\n"
"<h2 style=\" margin-top:16px; ma"
                        "rgin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:700;\">4. Configure AI Models: Set Model Paths &amp; Configuration </span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Purpose:</span> The <span style=\" font-style:italic;\">Configure AI Models</span> page allows authorized users to configure the AI models used for predictions and analyses. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Key Features:</span> </p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Model "
                        "Configuration:</span> Choose different AI models and configure their paths, including training datasets and other relevant parameters. </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">AI Model Paths:</span> Define where models are stored or how they are accessed for prediction tasks. </li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Use Case:</span> A data scientist or technical team member may use this page to set up or update the AI model\u2019s configuration based on new datasets or objectives. </li></ul>\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:700;\">5. User Management: Manage Profiles, Users, &amp; Permissions </span></h2>\n"
"<p style=\" margi"
                        "n-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Purpose:</span> The <span style=\" font-style:italic;\">User Management</span> page lets administrators manage user profiles, including password changes, and adding or removing users. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Key Features:</span> </p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Profile Management:</span> Change your own user details, such as the password or personal information. </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">"
                        "<span style=\" font-weight:700;\">Admin Features:</span> Admin users can add new users, modify user roles, or delete inactive users. </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Permissions Control:</span> Admins can assign specific roles or permissions, ensuring only authorized users have access to critical sections of the application. </li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Use Case:</span> If you are an admin, you can manage user access to sensitive areas like the <span style=\" font-style:italic;\">Alert</span> page or <span style=\" font-style:italic;\">Configure AI Models</span> page. </li></ul>\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-w"
                        "eight:700;\">6. Settings: Adjust General Application Settings </span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Purpose:</span> The <span style=\" font-style:italic;\">Settings</span> page is where users can adjust general app preferences for a personalized experience. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Key Features:</span> </p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Application Preferences:</span> Customize the app\u2019s appearance, notifications, language, and other basic settings. </li>\n"
"<li style=\" margin-top:0px; margin"
                        "-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Security Settings:</span> Set security preferences for login, password recovery, and other essential app features. </li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Use Case:</span> Change language settings or adjust notification preferences to suit your personal or organizational requirements. </li></ul>\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:700;\">7. Analysis Report: Graphical Reports of Inference/Application Data </span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Purpose:</span> The <span style=\" font-style:italic;\">A"
                        "nalysis Report</span> page provides graphical representations of the data collected through the application, including model inferences and real-time monitoring. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Key Features:</span> </p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Graphical Representation:</span> View insights such as species activity trends, model accuracy, and system performance over time in chart formats. </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Export Options:</span> Reports can be downloaded or shared with stakeholders for fur"
                        "ther analysis or action. </li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Use Case:</span> Generate reports for researchers, supervisors, or forest authorities to review the success and performance of the wildlife monitoring efforts. </li></ul></body></html>", None))
        self.analysisPage_back_btn.setText(QCoreApplication.translate("AppUI", u"Back", None))
        self.label_39.setText(QCoreApplication.translate("AppUI", u"Analysis Report", None))
        self.label_39.adjustSize()
        self.label_40.setText("")
    # retranslateUi

